export const actionTypes = {
     GET_ALL_PRODUCTS : 'GET_ALL_PRODUCTS',
     SET_CURRENT_PRODUCT : 'SET_CURRENT_PRODUCT',
     GET_ALL_CATEGORIES : 'GET_ALL_CATEGORIES',
     SET_NEW_CATEGORY : 'SET_NEW_CATEGORY',
     SET_LOADER : 'SET_LOADER',
     SET_DASHBOARD : 'SET_DASHBOARD',
     SET_TOKEN: 'SET_TOKEN',
     ADD_NEW_USER: 'ADD_NEW_USER',
     
     
}