export const actionTypes = {
     GET_ALL_PRODUCTS : 'GET_ALL_PRODUCTS',
     SET_CURRENT_PRODUCT : 'SET_CURRENT_PRODUCT',
     SET_CATEGORY_LIST : 'GET_ALL_CATEGORIES',
     SET_NEW_CATEGORY : 'SET_NEW_CATEGORY',
     SET_LOADER : 'SET_LOADER',
     SET_DASHBOARD : 'SET_DASHBOARD',
     SET_TOKEN: 'SET_TOKEN',
     ADD_NEW_USER: 'ADD_NEW_USER',
     SET_SINGLE_CATEGORY_FOR_EDIT: 'SET_SINGLE_CATEGORY_FOR_EDIT',
     SET_USER_LIST: 'SET_USER_LIST',
     SET_CURRENT_USER: 'SET_CURRENT_USER',
}